### ISSUE TITLE
Suggestion: Split localizedMessages.json further

### ISSUE THREAD

**Issue by jfaMan** [FusionAuth/fusionauth-node-cli#1]
When downloading, it would be helpful for development if localizedMessages.json could be further split into individual txt files for each language similar to how it was originally done in the [helper](https://github.com/FusionAuth/fusionauth-theme-helper) tool.

**Comment by ColinFrick** [comment]
That makes sense. I missed that when refactoring.

**Comment by ColinFrick** [comment]
This should be fixed as soon as 1.1.0 is released

@mooreds Could you please publish the new version on npm? Thanks

**Comment by jfaMan** [comment]
Thank you @ColinFrick

**Comment by mooreds** [comment]
1.1.0 is released.  https://www.npmjs.com/package/@fusionauth/cli

Thanks for filing the issue @jfaMan ! Thanks for the fix @ColinFrick !

**Comment by jfaMan** [comment]
@mooreds Looks like the 1.1.0 on npm is still using the old build. Could you rebuild it?

**Comment by mooreds** [comment]
Thank you for the PR. Are things okay now?

**Comment by ColinFrick** [comment]
@mooreds it’s still the version 1.1.0 on npmjs. I don’t think you can re-release it with the same version.

**Comment by jfaMan** [comment]
Yes, the dist folder still has the 1.0.1 build on npmjs

**Comment by mooreds** [comment]
Sorry folks, I'm new to publishing to npm.

I bumped the version to 1.1.1, ran `npm run build` and then `npm publish`. 

Does it work as expected now, @ColinFrick @jfaMan ?

If so, I can bump the version used by the theme helper too.

**Comment by ColinFrick** [comment]
@mooreds Looks good. To bump the version (including the one in `package-lock.json`) you can just run `npm version major|minor|patch`. The command also creates a commit with a version tag.

I'll also adjust the `package.json` to automatically run `build` when publishing.

**Comment by mooreds** [comment]
Great, thanks. While you are in there, can you please update the `Release` section of the README to include the `npm version` command?

**Comment by jfaMan** [comment]
@mooreds Yeah, after updating the helper to 1.1.1 too it's working now. Thanks!
