### ISSUE TITLE
Add commands for email templates

### ISSUE THREAD

**Issue by ColinFrick** [FusionAuth/fusionauth-node-cli#2]
There should be similar commands for working with email templates:
- `email:download` - Download all email templates to a directory
- `email:upload` - Upload all email templates from a directory
- `email:watch` - Watch a directory for changes

Handling for HTML / Text templates and localization must be implemented.

For consideration:
- `email:test` - Send a test email through FusionAuth to the given email address
- Should the base information of the email (Name, Default Subject, From Email, Default from name) also be exported / modifiable?

**Comment by mooreds** [comment]
This would be cool. I'd suggest that you have the following folder structure under the TMP dir:

```
emails/
   default/
      9dd63c26-5c18-4f9e-aa03-d414b05e529f/
         html_body.html
         text_body.txt
         name.txt
         default_subject.txt
         from_email.txt
         default_from_name.txt
      3bd2a8c6-513f-4fc3-908f-7cb68e743893/
   en/
   de/
```

So the pattern is `email/locale/template_id` and all the files needed to patch the email object are stored in that directory.

**Comment by ColinFrick** [comment]
Because the localized templates are contained in the email object itself wouldn't it make more sense to structure the directory like this?
```
emails/
    9dd63c26-5c18-4f9e-aa03-d414b05e529f/
        name.txt
        from_email.txt
        default/
            html_body.txt
            text_body.txt
            from_name.txt
            subject.txt
        af_NA/
            html_body.txt
            text_body.txt
            from_name.txt
            subject.txt
        de/

**Comment by mooreds** [comment]
Ah, good point. Makes sense.
