### ISSUE TITLE
Support pulling down a theme from the command line

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-node-cli#3]
Right now we require an environment file. It would be nice to be override elements of it (particularly theme id and tmp dir name) from the command line.

**Comment by ColinFrick** [comment]
@mooreds That's already possible with the CLI, do you mean extending the https://github.com/FusionAuth/fusionauth-theme-helper/ `download.sh` / `upload.sh` ?

Theme helper just uses the environment variables from the `.env` file:
`npx fusionauth theme:download $THEME_ID -k $API_KEY -o $TMP_DIR -h $FUSIONAUTH_URL`

**Comment by mooreds** [comment]
Ah, I didn't know that. I think this issue can be closed.
